version: '3'

services:
  db:
    image: postgres
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment: 
      - POSTGRESQL_HOST=$DB_HOST
      - POSTGRES_USER=$DB_USER  
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - 5432:5432
  api:
    build: ./api/
    command: /bin/sh -c "rm -f /$WORKDIR/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/$WORKDIR
      - ./api/vendor/bundle:/$WORKDIR/vendor/bundle
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    ports:
      - $API_PORT:$CONTAINER_PORT
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  postgres-data:
